### ISSUE TITLE
Reported round duration is very often 1 tick longer than actual

### ISSUE THREAD

**Issue by equirs** [SkylerPIlot/Ba-Minigame#11]
From [this](https://discord.com/channels/235552132151902210/235552132151902210/1054923166511792269) discussion in SBA. The way they measure round time is by the appearance of the "Loading" text going into wave 1 and after the queen kill. The way the plugin measures round time is by the game message going into wave 1 and the appearance of the rewards widget after wave 10 ends. This widget is almost always going to appear 1t after the players load out of the BA instance. 

I believe it's possible to use either a game state or player change subscriber to determine wave/round starts and ends. The round time announcement doesn't necessarily have to stop the timer at that point; it should probably stop sooner and let the widget determine point values before announcing.

**Comment by SkylerPIlot** [comment]
The plugin already tracks what their current wave is, I believe the varbits for game area are set before the teleport out of the area occurs. I can make a fix that uses this method of using a varbit change and place it on a new branch for testing I don't do much speeding, so it would need to be tested by that community if it were to be an acceptable change. @equirs
