### ISSUE TITLE
Ba Minigame Plugin

### ISSUE THREAD

**Issue by ghost** [SkylerPIlot/Ba-Minigame#2]
Hi there, 

The plugin doesn't highlight the arrows depending on attack styles.

Can you please look into it :) @SkylerPIlot 

First Github post lol..

**Comment by ransty** [comment]
Have you checked the settings for the plugin? Seems to work for me.

**Comment by ffalor** [comment]
Just downloaded, and doesnt highlight for me either. None of the roles do.

**Comment by equirs** [comment]
This config setting no longer defaults to "disabled" (which probably should never have been an option, but now it's a bit late to change it)
