### ISSUE TITLE
randomly forgets to highlight which poison the healer needs to use and causes me to loose points and sometimes rounds

### ISSUE THREAD

**Issue by anon2828226** [SkylerPIlot/Ba-Minigame#6]
Literally just why? having an inconsistent help like that is genuinely worse than nothing.

**Comment by equirs** [comment]
Can you provide more information? Are you talking about the poisoned food highlights? Are you sure it's not because of call changes? Is your defender not calling for you, or are they calling incorrectly?

**Comment by SkylerPIlot** [comment]
I encountered this bug in a relatively rare use case hence why nobody else has reported this issue.

Food highlights will turn off when the correct food is called initially by the defender and then another person calls from the horn. When called from the big horn a chat message of "Call correction: XXX" and the food highlight turns itself off.

Honestly this case never occurs in Funs or Leeches in the advanced ba community and is a super rare case even in general 306 play. If anyone cares to fix feel free to pr, but it is super low priority.
